# Generated by Django 2.2.8 on 2020-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alma_eskolar', '0002_subdistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
