# Generated by Django 2.2.8 on 2020-01-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alma_eskolar', '0004_auto_20200122_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapPoint',
            new_name='EbcMap',
        ),
    ]
