# Generated by Django 2.2.8 on 2020-03-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alma_eskolar', '0007_auto_20200201_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subdistrict',
            new_name='District',
        ),
    ]
