# Generated by Django 2.2.8 on 2020-05-05 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alma_eskolar', '0008_auto_20200327_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebcmap',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipality', to='alma_eskolar.District'),
        ),
        migrations.AddField(
            model_name='ebcmap',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos', verbose_name='Eskola Photo'),
            preserve_default=False,
        ),
    ]
