# Generated by Django 2.2.8 on 2020-05-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alma_eskolar', '0010_auto_20200528_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
