# Generated by Django 2.2.8 on 2020-08-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alma_eskolar', '0011_auto_20200528_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebcmap',
            name='municipality',
        ),
        migrations.AddField(
            model_name='ebcmap',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='alma_eskolar.District'),
        ),
    ]
